// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAnmIAQUP8MoXEE9FfEvf7A88jgbX1Zr0',
    appId: '1:346168213826:web:4b113a9ffd0617c1bac8db',
    messagingSenderId: '346168213826',
    projectId: 'pv239-qwiz',
    authDomain: 'pv239-qwiz.firebaseapp.com',
    storageBucket: 'pv239-qwiz.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfQaSuY_AGOThTw9l8-iPF53-1BIZwyGw',
    appId: '1:346168213826:android:0d362c1e7f402513bac8db',
    messagingSenderId: '346168213826',
    projectId: 'pv239-qwiz',
    storageBucket: 'pv239-qwiz.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6Q1I_8dACSzoKwwWMiT3h3x05ps9ipcI',
    appId: '1:346168213826:ios:2e1957787076ba45bac8db',
    messagingSenderId: '346168213826',
    projectId: 'pv239-qwiz',
    storageBucket: 'pv239-qwiz.appspot.com',
    iosClientId: '346168213826-766t3uf3hh1rn1bj3rv7g6k5tti3tukg.apps.googleusercontent.com',
    iosBundleId: 'com.example.pv239Qwiz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6Q1I_8dACSzoKwwWMiT3h3x05ps9ipcI',
    appId: '1:346168213826:ios:2e1957787076ba45bac8db',
    messagingSenderId: '346168213826',
    projectId: 'pv239-qwiz',
    storageBucket: 'pv239-qwiz.appspot.com',
    iosClientId: '346168213826-766t3uf3hh1rn1bj3rv7g6k5tti3tukg.apps.googleusercontent.com',
    iosBundleId: 'com.example.pv239Qwiz',
  );
}
